const express=require("express");
const userController=require('../controller/userController')
const adminController=require('../controller/adminController')
const {authentication}=require('../middleware/authentication')
const router=express.Router();
router.post('/signUp',userController.signUp)
router.post('/logIn',userController.logIn)
router.post('/logOut',authentication,userController.logOut)
router.post('/userDelete',authentication,userController.userDelete)
router.post('/forgetpassword',authentication,userController.forgetpassword)
router.post('/editProfile',authentication,userController.editProfile)
router.post('/changePassword',authentication,userController.changePassword)
router.post('/notificationCreate',authentication,userController.notificationCreate)
router.get('/notificationGet',authentication,userController.notificationGet)
router.post('/editNotification',authentication,userController.editNotification)
router.post('/clearNotification',authentication,userController.clearNotification)
router.post('/address',authentication,userController.address)
router.post('/editAddress',authentication,userController.editAddress)
router.post('/deleteAddress',authentication,userController.deleteAddress)
router.post('/cartData',authentication,userController.cartData)
router.post('/category',authentication,adminController.category)
router.post('/editCategory',authentication,adminController.editCategory)
router.post('/deleteCategory',authentication,adminController.deleteCategory)
router.post('/productAdded',authentication,adminController.productAdded)
router.post('/productEdit',authentication,adminController.productEdit)
router.post('/deleteProduct',authentication,adminController.deleteProduct)
router.post('/productImage',authentication,adminController.productImage)
router.post('/productImageEdit',authentication,adminController.productImageEdit)
router.post('/productImageDelete',authentication,adminController.productImageDelete)
router.post('/cartDataEdit',authentication,userController.cartDataEdit)
router.post('/cartDataDeleted',authentication,userController.cartDataDeleted)
router.post('/bookingCreate',authentication,userController.bookingCreate)
router.post('/bookingEdit',authentication,userController.bookingEdit)
router.post('/bookingDeleted',authentication,userController.bookingDeleted)
router.get('/getproduct',authentication,userController.getproduct)
module.exports=router