const express=require("express");
const userController=require('../controller/userController')
const adminController=require('../controller/adminController')
const driverController=require('../controller/driverController')
const {authentication}=require('../middleware/authentication')
const router=express.Router();
router.post('/sidIdGenerateTwilio',userController.sidIdGenerateTwilio)
router.post('/signUp',userController.signUp)
router.post('/login',userController.login)
router.post('/logOut',authentication,userController.logOut)
router.post('/userDelete',authentication,userController.userDelete)
router.post('/forgetpassword',authentication,userController.forgetpassword)
router.post('/editProfile',authentication,userController.editProfile)
router.post('/changePassword',authentication,userController.changePassword)
router.post('/clearNotification',authentication,userController.clearNotification)
router.post('/address',authentication,userController.address)
router.post('/editAddress',authentication,userController.editAddress)
router.post('/deleteAddress',authentication,userController.deleteAddress)
router.post('/cartData',authentication,userController.cartData)
router.post('/category',authentication,adminController.category)
router.post('/editCategory',authentication,adminController.editCategory)
router.post('/deleteCategory',authentication,adminController.deleteCategory)
router.post('/productAdded',authentication,adminController.productAdded)
router.post('/productEdit',authentication,adminController.productEdit)
router.post('/deleteProduct',authentication,adminController.deleteProduct)
router.post('/cartDataDeleted',authentication,userController.cartDataDeleted)
router.get('/getproduct',authentication,userController.getproduct)
router.post('/addressDefault',authentication,userController.addressDefault)
router.post('/subscriptionCreate',authentication,adminController.subscriptionCreate)
router.post('/subscriptionBuy',authentication,userController.subscriptionBuy)
router.post('/subscriptionEdit',authentication,adminController.subscriptionEdit)
router.post('/subscriptionDelete',authentication,adminController.subscriptionDelete)
router.post('/AddCartItem',authentication,userController.AddCartItem)
router.post('/UpdateCart',authentication,userController.UpdateCart)
router.post('/DeleteCart',authentication,userController.DeleteCart)
router.post('/checkout',authentication,userController.checkout)
router.post('/orderList',authentication,userController.orderList)
router.post('/orderDetails',authentication,userController.orderDetails)
router.post('/orderAssign',authentication,userController.orderAssign)
router.get('/driverlist',authentication,userController.driverlist)
router.post('/createStore',authentication,userController.createStore)
router.post('/storeProduct',authentication,userController.StoreProduct)
router.post('/productReview',authentication,userController.productReview)
router.post('/createLike',authentication,userController.createLike)
router.post('/countLikes',authentication,userController.countLikes),
router.get('/productListing',authentication,userController.productListing)
router.post('/paymentCreateCOD',authentication,userController.paymentCreateCOD)
router.post('/createstripe',authentication,userController.createstripe)
router.get('/getToken',authentication,userController.getToken)
router.post('/createCard',authentication,userController.createCard)
router.post('/cardList',authentication,userController.cardList)
router.post('/createPayment',authentication,userController.createPayment)
router.get("/generatePdfFromApi",userController.generatePdfFromApi);
router.post('/stripeIntent',authentication,userController.stripeIntent)
router.post("/orders",authentication,driverController.orders)
router.post('/productCount',authentication,driverController.productCount)
router.post('/updateDriverStatus',authentication,driverController.updateDriverStatus)
module.exports=router