module.exports=(Sequelize,sequelize,DataTypes) =>
{
    return sequelize.define(
        "addressTable",
        {
            ...require('./core')(Sequelize,DataTypes),
            userId:
            {
                type:Sequelize.UUID,
                allowNull:true,
                references:
                {
                    model:"userTable",
                    key:"id"
                },
                onUpdate:"CASCADE",
                onDelete:"CASCADE"
            },
            country:
            {
                type:DataTypes.STRING(225),
                allowNull:true
            },
            state:
            {
                type:DataTypes.STRING(225),
                allowNull:true
            },
            city:
            {
                type:DataTypes.STRING(225),
                allowNull:true
            },
            hnumber:
            {
                type:DataTypes.STRING(225),
                allowNull:true
            },
            isDefault:
            {
                type:DataTypes.INTEGER,
                allowNull:true,
                defaultValue:0  //0  for not default 1 for default
            }
        },
        {
            tableName:"addressTable"
        }
    )
}