module.exports=(Sequelize,sequelize,DataTypes) =>
{
    return sequelize.define(
        "cartTable",
        {
            ...require('./core')(Sequelize,DataTypes),
            productId:
            {
                type:Sequelize.UUID,
                allowNull:true,
                references:
                {
                    model:"productTable",
                    key:"id"
                },
                onUpdate:"CASCADE",
                onDelte:"CASCADE"
            },
            Quantity:
            {
                type:DataTypes.STRING(225),
                allowNull:true
            }
        },
        {
            tableName:"cartTable"
        }
    )
}