module.exports=(Sequelize,sequelize,DataTypes)=>
{
    return sequelize.define(
        "likeTable",
        {
            ...require('./core')(Sequelize,DataTypes),
            userId:
            {
                type:Sequelize.UUID,
                allowNull:true,
                references:
                {
                    model:"userTable",
                    key:"id"
                },
                onUpdate:"CASCADE",
                onDelete:"CASCADE"
            },
            ReviewId:
            {
                type:Sequelize.UUID,
                allowNull:true,
                references:
                {
                    model:"productReviewTable",
                    key:"id"
                },
                onUpdate:"CASCADE",
                onDelete:"CASCADE"
            }
        },
        {
            tableName:"likeTable"
        }
    )
}