module.exports=(Sequelize,sequelize,DataTypes) =>
{
    return sequelize.define(
        "notificationTable",
        {
            ...require('./core')(Sequelize,DataTypes),
            senderId:
            {
                type:Sequelize.UUID,
                allowNull:true,
                references:
                {
                    model:"userTable",
                    key:"id"
                },
                onUpdate:"CASCADE",
                onDelete:"CASCADE"
            },
            receiverId:
            {
                type:Sequelize.UUID,
                allowNull:true,
                references:
                {
                    model:"userTable",
                    key:"id"
                },
                onUpdate:"CASCADE",
                onDelete:"CASCADE"
            },
            title:
            {
                type:DataTypes.STRING(225),
                allowNull:true
            },
            message:
            {
                type:DataTypes.TEXT("long"),
                allowNull:true
            },
            isRead:
            {
                type:DataTypes.INTEGER,
                allowNull:true,
                defaultValue:0  //0 for not read 1 for read
            },
            bookingId:
            {
                type:Sequelize.UUID,
                allowNull:true,
                references:
                {
                    model:"bookingTable",
                    key:"id"
                },
                onDelete:"CASCADE",
                onUpdate:"CASCADE"
            },
            isnotification:
            {
                type:DataTypes.INTEGER,
                allowNull:true,
                defaultValue:0   //0 for notification on and 1 for ON
            },
        },
        {
            tableName:"notificationTable"
        }
    )
}