module.exports=(Sequelize,sequelize,DataTypes) =>
{
    return sequelize.define(
        "orderTable",
        {
            ...require('./core')(Sequelize,DataTypes),
            userId:
            {
                type:Sequelize.UUID,
                allowNull:true,
                references:
                {
                    model:"userTable",
                    key:"id"
                },
                onUpdate:"CASCADE",
                onDelete:"CASCADE"
            },
            addressId:
            {
              type:Sequelize.UUID,
              allowNull:true,
              references:
              {
                model:"addressTable",
                key:"id"
              },
              onUpdate:"CASCADE",
              onDelete:"CASCADE"
            },
            Amount:
            {
                type:DataTypes.DOUBLE,
                allowNull:true
            },
            status:
            {
                type:DataTypes.INTEGER,
                allowNull:true,
                defaultValue:1
            },
            storeId:
            {
                type:Sequelize.UUID,
                allowNull:true,
                references:
                {
                    model:"storeTable",
                    key:"id"
                },
                onUpdate:"CASCADE",
                onDelete:"CASCADE"
            },
            assignDriverId:
            {
                type:Sequelize.UUID,
                allowNull:true,
                references:
                {
                    model:"userTable",
                    key:"id"
                },
                onUpdate:"CASCADE",
                onDelete:"CASCADE"
            }
        },
        {
            tableName:"orderTable"
        }
    )
}