module.exports=(Sequelize,sequelize,DataTypes) =>
{
    return sequelize.define(
        "subscriptionBuyTable",
        {
            ...require('./core')(Sequelize,DataTypes),
            userId:
            {
                type:Sequelize.UUID,
                allowNull:true,
                references:
                {
                    model:"userTable",
                    key:"id"
                },
                onUpdate:"CASCADE",
                onDelete:"CASCADE"
            },
            subscriptionId:
            {
                type:Sequelize.UUID,
                allowNull:true,
                references:
                {
                    model:"subscriptionTable",
                    key:"id"
                },
                onUpdate:"CASCADE",
                onDelete:"CASCADE"
            },
            startDate:
            {
                type:DataTypes.DATE,
                defaultValue:DataTypes.NOW(0),
                allowNull:true
            },
            EndDate:
            {
               type:DataTypes.DATE,
               defaultValue:DataTypes.NOW(0),
               allowNull:true
            }
        },
        {
            tableName:"subscriptionBuyTable"
        }
    )
}