module.exports=(Sequelize,sequelize,DataTypes) =>
{
    return sequelize.define(
        "userTable",
        {
         ...require('./core')(Sequelize,DataTypes),
         firstName:
         {
            type:DataTypes.STRING(100),
            allowNull:true
         },
         lastName:
         {
            type:DataTypes.STRING(225),
            allowNull:true
         },
         email:
         {
            type:DataTypes.STRING(225),
            allowNull:true,
         },
         password:
         {
            type:DataTypes.STRING(225),
            allowNull:true
         },
         phoneNumber:
         {
            type:DataTypes.STRING(225),
            allowNull:true,
         },
        countryCode:
        {
           type:DataTypes.STRING(225),
           allowNull:true
        },
        profile:
        {
         type:DataTypes.STRING(225),
         allowNull:true
        },
        devicetoken:
        {
         type:DataTypes.STRING(225),
         allowNull:true,
         defaultValue:null
        }    
 },
 {
    tableName:"userTable"
 }
    )
}