module.exports=(Sequelize,sequelize,DataTypes) =>
{
    return sequelize.define(
        "userTable",
        {
         ...require('./core')(Sequelize,DataTypes),
         firstName:
         {
            type:DataTypes.STRING(100),
            allowNull:true
         },
         lastName:
         {
            type:DataTypes.STRING(225),
            allowNull:true
         },
         email:
         {
            type:DataTypes.STRING(225),
            allowNull:true,
         },
         password:
         {
            type:DataTypes.STRING(225),
            allowNull:true
         },
         phoneNumber:
         {
            type:DataTypes.STRING(225),
            allowNull:true,
         },
        countryCode:
        {
           type:DataTypes.STRING(225),
           allowNull:true
        },
        profile:
        {
         type:DataTypes.STRING(225),
         allowNull:true
        },
        devicetoken:
        {
         type:DataTypes.STRING(225),
         allowNull:true,
         defaultValue:null
        } ,
        role:
        {
         type:DataTypes.INTEGER,
         defaultValue:1    //1 user 2 driver 3 seller
        },
        isOnline:
        {
         type:DataTypes.INTEGER,
         defaultValue:0   //0 for offline   1 for online
        },
        isorderassign:
        {
         type:DataTypes.INTEGER,
         defaultValue:0    //0 for assign  1 for not assign
        },
        location:
        {
         type:DataTypes.STRING(225),
         allowNull:true
        },
        latitude:
        {
         type:DataTypes.STRING(225),
         allowNull:true
        },
        longitude:
        {
           type:DataTypes.STRING(225),
           allowNull:true
        },
        status:
        {
         type:DataTypes.INTEGER,
         allowNull:true,
         defaultValue:0   //0 for dispatching  1 for out for delivery and 2 for delivered!
        },
        customerId:
        {
         type:DataTypes.STRING(225),
         allowNull:true,
         defaultValue:null
        }
 },
 {
    tableName:"userTable"
 }
    )
}